# Generated by Django 5.1.3 on 2024-12-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foundpost_lostpost_petimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
