# Generated by Django 5.1.3 on 2024-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foundpost_is_archived_lostpost_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpost',
            name='reward',
            field=models.TextField(blank=True, help_text="Enter a reward amount. Leave blank if you don't want to offer a reward.", null=True),
        ),
    ]
