# Generated by Django 5.1.3 on 2024-12-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_somerelatedmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeRelatedModel',
        ),
    ]
