# Generated by Django 5.1.3 on 2024-12-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_petimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostpost',
            name='image',
        ),
    ]
